# Generated by Django 3.2.4 on 2021-06-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Усі міста', 'verbose_name_plural': 'Міста'},
        ),
    ]
