# Generated by Django 3.2.4 on 2021-06-28 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0003_auto_20210628_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Номер поїзда')),
                ('travel_time', models.PositiveSmallIntegerField(verbose_name='Час путі')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city_set', to='cities.city', verbose_name='З міста')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city_set', to='cities.city', verbose_name='У місто')),
            ],
            options={
                'verbose_name': 'Поїзд',
                'verbose_name_plural': 'Поїзда',
                'ordering': ['travel_time'],
            },
        ),
    ]
